project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Student Studentson"
  date: "2023-08-15"
  chapters:
    - index.qmd
    - 01-reliability-tools.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



